// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftverskaRealizacijaBackend.Infrastructure;

#nullable disable

namespace SoftverskaRealizacijaBackend.Migrations
{
    [DbContext(typeof(CRUDContext))]
    partial class CRUDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoftverskaRealizacijaBackend.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipKorisnika")
                        .HasColumnType("int");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("SoftverskaRealizacijaBackend.Models.Kvar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<int>("StanjeKvara")
                        .HasColumnType("int");

                    b.Property<DateTime>("VremeOtkanjanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremePrijave")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("NodeId");

                    b.ToTable("Kvraovi");
                });

            modelBuilder.Entity("SoftverskaRealizacijaBackend.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Nodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 45.239600000000003,
                            Longitude = 19.822700000000001
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 45.239600000000003,
                            Longitude = 19.829699999999999
                        });
                });

            modelBuilder.Entity("SoftverskaRealizacijaBackend.Models.NodeConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EndPinId")
                        .HasColumnType("int");

                    b.Property<int>("StartPinId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NodeConnections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndPinId = 2,
                            StartPinId = 1
                        });
                });

            modelBuilder.Entity("SoftverskaRealizacijaBackend.Models.Kvar", b =>
                {
                    b.HasOne("SoftverskaRealizacijaBackend.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftverskaRealizacijaBackend.Models.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Node");
                });
#pragma warning restore 612, 618
        }
    }
}
