// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftverskaRealizacijaBackend.Infrastructure;

#nullable disable

namespace SoftverskaRealizacijaBackend.Migrations
{
    [DbContext(typeof(CRUDContext))]
    partial class CRUDContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoftverskaRealizacijaBackend.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipKorisnika")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("SoftverskaRealizacijaBackend.Models.Kvar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<int>("StanjeKvara")
                        .HasColumnType("int");

                    b.Property<DateTime>("VremeOtkanjanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremePrijave")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("NodeId");

                    b.ToTable("Kvraovi");
                });

            modelBuilder.Entity("SoftverskaRealizacijaBackend.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("NodeConnectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NodeConnectionId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("SoftverskaRealizacijaBackend.Models.NodeConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TopNodeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopNodeId");

                    b.ToTable("NodeConnections");
                });

            modelBuilder.Entity("SoftverskaRealizacijaBackend.Models.Kvar", b =>
                {
                    b.HasOne("SoftverskaRealizacijaBackend.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoftverskaRealizacijaBackend.Models.Node", "Node")
                        .WithMany("Kvarovi")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("SoftverskaRealizacijaBackend.Models.Node", b =>
                {
                    b.HasOne("SoftverskaRealizacijaBackend.Models.NodeConnection", null)
                        .WithMany("Nodes")
                        .HasForeignKey("NodeConnectionId");
                });

            modelBuilder.Entity("SoftverskaRealizacijaBackend.Models.NodeConnection", b =>
                {
                    b.HasOne("SoftverskaRealizacijaBackend.Models.Node", "TopNode")
                        .WithMany()
                        .HasForeignKey("TopNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopNode");
                });

            modelBuilder.Entity("SoftverskaRealizacijaBackend.Models.Node", b =>
                {
                    b.Navigation("Kvarovi");
                });

            modelBuilder.Entity("SoftverskaRealizacijaBackend.Models.NodeConnection", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
